### ISSUE TITLE
Article Titles Open in New Tab Instead of Expanding

### ISSUE THREAD

**Issue by Wendigogo** [Joedmin/xExtension-readeck-button#2]
Describe the bug
When viewing the article stream, clicking on an article title should expand the article content below. However, I'm consistently experiencing an issue where clicking on the article title opens the article's origin website in a new tab.

To expand the article, I have to click on the timestamp located to the right of the article title.

I was able to expand articles as expected when I have disabled the extension.

To Reproduce
1. Go to 'main stream' (or any label)
2. Click on 'any article title'
3. Observe that it has opened in a new tab to the 3rd party site as the hyperlink suggested

Expected behavior
The article should have expanded.

This is the exact same issue as [https://github.com/christian-putzke/freshrss-pocket-button/issues/4](https://github.com/christian-putzke/freshrss-pocket-button/issues/4) (that I copy-paste text 😅) so probably the solution is probably given there too (related commit : [https://github.com/christian-putzke/freshrss-pocket-button/commit/9052884687893decd7d05b0fccc2716bc9e5b173](https://github.com/christian-putzke/freshrss-pocket-button/commit/9052884687893decd7d05b0fccc2716bc9e5b173).

Thanks for your help.

**Comment by Wendigogo** [comment]
I just grab V0.5 `entry_header.phtml` and `entry_bottom.phtml` from "Pocket Button" repository, search&replace `pocket` with `readeck` and replace related files with these on my server.

Problem solved !

I'm not familiar with Github so I attached correct files here:
[correct_entries.zip](https://github.com/user-attachments/files/17409661/correct_entries.zip)

 I hope this helps.

**Comment by Joedmin** [comment]
Hi, thank you very much for reporting this issue and it's fix. I'me getting on it right now to update it as soon as possible

**Comment by Joedmin** [comment]
Fixed it and released [Version 0.4](https://github.com/Joedmin/xExtension-readeck-button/releases/tag/0.4)

**Comment by Wendigogo** [comment]
Wow, that was fast !

Do you think you could replicate your extension but for Wallabag APIs ? I opened an issue in FressRSS repository but no-one seems to care ([https://github.com/FreshRSS/FreshRSS/issues/6874](https://github.com/FreshRSS/FreshRSS/issues/6874))?

Readeck is (really) great but it lacks of a native app.

**Comment by Joedmin** [comment]
Yeah sure, it's just using another API with the already existing code 😁 

I know about the absence of the absence of native app for Readeck and I want to try to write it some day

**Comment by Joedmin** [comment]
Wallabag Extension can be found here https://github.com/Joedmin/xExtension-wallabag-button 😇
